AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  notification-test
  
  Sample SAM Template for notification-test

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 5
    MemorySize: 128

Parameters:
  SlackOAuthToken:
    Type: AWS::SSM::Parameter::Value<String>
    Default: '/notification-slack/oauthtoken'
  SlackChannel:
    Type: AWS::SSM::Parameter::Value<String>
    Default: '/notification-slack/channel'

Resources:
  NotificationSlackdFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: notification-slack/
      Handler: bootstrap
      Runtime: provided.al2
      Architectures:
        - x86_64
      Policies:
      - SSMParameterReadPolicy:
          ParameterName: "notification-slack/oauthtoken"
      Events:
        DeploySuceeded:
          Type: CloudWatchEvent
          Properties:
            Pattern:
              source:
                - aws.codepipeline
              detail-type:
                - CodePipeline Pipeline Execution State Change
              detail:
                state:
                - SUCCEEDED
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          SLACK_OAUTH_TOKEN: !Ref SlackOAuthToken
          SLACK_CHANNEL: !Ref SlackChannel

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  # HelloWorldAPI:
  #   Description: "API Gateway endpoint URL for Prod environment for First Function"
  #   Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  NotificationSlackdFunction:
    Description: "NotificationSlack Lambda Function ARN"
    Value: !GetAtt NotificationSlackdFunction.Arn
  NotificationSlackdFunctionIamRole:
    Description: "Implicit IAM Role created for NotificationSlack function"
    Value: !GetAtt NotificationSlackdFunctionRole.Arn
